# Generated by Django 5.0.9 on 2024-09-21 20:45

import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_static_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticroute',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
