# Generated by Django 5.0.9 on 2025-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_static_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticroute',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='staticroute',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='staticroute',
            index=models.Index(fields=['scope_type', 'scope_id'], name='netbox_stat_scope_t_9cda48_idx'),
        ),
    ]
