# Generated by Django 5.0.9 on 2025-02-02 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0191_module_bay_rebuild'),
        ('extras', '0121_customfield_related_object_filter'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_static_routes', '0002_alter_staticroute_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticroute',
            old_name='next_hop',
            new_name='next_hop_ip',
        ),
        migrations.AddField(
            model_name='staticroute',
            name='metric',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='staticroute',
            name='nh_int_scope_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticroute',
            name='nh_int_scope_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model__in', ('interface', 'vminterface'))), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='staticroute',
            index=models.Index(fields=['nh_int_scope_type', 'nh_int_scope_id'], name='netbox_stat_nh_int__d9b36f_idx'),
        ),
    ]
