# Generated by Django 5.0.9 on 2024-09-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_static_routes', '0002_alter_staticroute_custom_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticroute',
            name='bfd',
            field=models.BooleanField(default=False),
        ),
    ]
